- name: Check Version Zabbix Agent
  hosts: all

  tasks:
  - name: Zabbix execute 
    ignore_errors: yes
    shell: "ps -ef | grep zabbix"
    register: running_processes
  - name: Waagent 
    shell: "cd WALinuxAgent"
    shell: "pwd"