- name: Update SO
  hosts: all

  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Check update SO
    ignore_errors: yes
    shell: "yum check-update"
    register: running_processes

  - name: Restart server
    ignore_errors: yes
    shell: "init 6"
    register: running_processes

