- name: Copy File
  hosts: all

  tasks:
    - name: Create Folder
      win_file:
        path: C:\Zabbix\teste
        state: directory

    - name: Create file zabbix_agentd.conf
      win_file:
        path: C:\Zabbix\teste\zabbix_agentd.conf
        state: touch
    
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\teste\zabbix_agentd.conf
        line: 
              'StartAgents=10 /n
              DebugLevel=3 \/n
              LogFile=c:\Zabbix\log\zabbix_agentd.log
              Timeout=30
              EnableRemoteCommands=1
              LogRemoteCommands=1
              Server=10.161.69.107,10.161.69.157,$name,$ip
              ServerActive=$name
              HostMetadataItem=system.uname
              Hostname=$hostName'
     
    - win_copy:
        src: /var/lib/awx/projects/_11__install_zabbix_agent/Zabbix/Agent/Windows/zabbix_agentd.exe
        dest: C:\Zabbix\teste\
    
    - win_copy:
        src: /var/lib/awx/projects/_11__install_zabbix_agent/Zabbix/Agent/Windows/zabbix_get.exe
        dest: C:\Zabbix\teste\
    
    - win_copy:
        src: /var/lib/awx/projects/_11__install_zabbix_agent/Zabbix/Agent/Windows/zabbix_sender.exe
        dest: C:\Zabbix\teste\
    - win_copy:
        src: /var/lib/awx/projects/_11__install_zabbix_agent/Zabbix/Agent/Windows/Limpeza_Maquina.bat
        dest: C:\Zabbix\teste\