- name: Copy File
  hosts: all

  tasks:
#  - win_copy:
#      src: C:\TEMP\new.txt
#      dest: C:\Zabbix\
#      remote_src: yes
#    - win_copy:
#        src: \\stefanini.dom\NETLOGON\Agent_Zabbix\WINDOWS\GPO_INSTALL\application\zabbix_agentd.exe
#        dest: C:\TEMP\
#        remote_src: yes
    - win_copy:
        src: /home/awx/zabbix.conf
        dest: C:\Zabbix\
#        remote_src: yes