- name: Teste de Variavel
  hosts: all

  tasks:
    - name: Add line file new.txt
      win_lineinfile:
        path: C:\TEMP\new.txt
        line: Hostname={{ansible_hostname}}
#    - debug:
#        msg: "{{ansible_all_ipv4_addresses}}"