- name: Teste de Variavel
  hosts: all

  tasks:
    - name: Add line file new.txt
      win_lineinfile:
        path: C:\TEMP\new.txt
        line: Hostname={{ hostvars['ansible_hostname'] }}
    - name: Add IP address of all hosts to all hosts
      win_lineinfile:
        path: C:\TEMP\new.txt
        line: {{ ansible_facts['ansible_hostname'] }}