- name: Install Zabbix Agent - Windows Server
  hosts: all

  tasks:
    - name: Add line file new.txt
      win_lineinfile:
        path: C:\TEMP\new.txt
        line: Hostname={{ hostvars['ansible_hostname'] }}