- name: Install Zabbix Agent - Windows Server
  hosts: all

  tasks:
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: Hostname={{ hostvars['ansible_hostname'] }}