- name: Teste de Variavel
  hosts: all

  tasks:
    - name: Add line file new.txt
      win_lineinfile:
        path: C:\TEMPS\new.txt
        line: Hostname={{ansible_hostname}}
    
    - win_copy:
        src: /var/lib/docker/data/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_agentd.exe
        dest: C:\TEMPS

#    - name: Delete Files App Zabbix Agent
#      win_file:
#        path: C:\TEMPS
#        state: absent
#    - debug:
#        msg: "{{ansible_all_ipv4_addresses}}"