- name: Install Zabbix Agent - Windows Server
  hosts: all

  tasks:
    - name: Create Folder
      win_file:
        path: C:\Zabbix
        state: directory
    - name: Create Folder
      win_file:
        path: C:\Zabbix\application
        state: directory
    - name: Create Folder
      win_file:
        path: C:\Zabbix\config
        state: directory
    - name: Create Folder
      win_file:
        path: C:\Zabbix\log
        state: directory
    - name: Create Folder
      win_file:
        path: C:\Zabbix\scripts
        state: directory

    - name: Create file zabbix_agentd.conf
      win_file:
        path: C:\Zabbix\config\zabbix_agentd.conf
        state: touch
    
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: StartAgents=10
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: DebugLevel=3
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: LogFile=c:\Zabbix\log\zabbix_agentd.log
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: Timeout=30
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: EnableRemoteCommands=1
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: LogRemoteCommands=1
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: Server={{serverzabbix}},{{ serverproxy }}
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: ServerActive={{ serverproxyactive }}
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: HostMetadataItem=system.uname
    - name: Add line file zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        line: HostnameItem=system.hostname
     
    - win_copy:
        src: /var/lib/docker/data/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_agentd.exe
        dest: C:\Zabbix\application\
    
    - win_copy:
        src: /var/lib/docker/data/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_get.exe
        dest: C:\Zabbix\application\
    
    - win_copy:
        src: /var/lib/docker/data/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_sender.exe
        dest: C:\Zabbix\application\
    - win_copy:
        src: /var/lib/docker/data/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/Limpeza_Maquina.bat
        dest: C:\Zabbix\scripts\

    - name: Install Zabbix Agent
      win_command: C:\Zabbix\application\zabbix_agentd.exe -i -c C:\Zabbix\config\zabbix_agentd.conf
      register: installzabbix_out
    
    - name: Start Zabbix Agent
      win_command: sc start "Zabbix Agent"
      register: startzabbix_out