- name: Install Zabbix Agent - Windows Server
  hosts: all

  tasks:
    - name: Install Zabbix Agent
      win_command: C:\Zabbix\application\zabbix_agentd.exe -i -c C:\Zabbix\config\zabbix_agentd.conf
      register: installzabbix_out

    - name: "Windows | Set service startup mode to auto and ensure it is started"
        win_service:
          name: Zabbix Agent
          start_mode: auto
          state: started
