- name: Install Zabbix Agent - Windows Server
  hosts: all

  tasks:
    - name: Delete Files App Zabbix Agent
      win_file:
        path: C:\Zabbix\config\zabbix_agentd.conf
        state: absent
    - name: Delete Files App Zabbix Agent
      win_file:
        path: C:\Zabbix\zabbix_agentd.conf
        state: absent
    
    - win_copy:
        src: /var/lib/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_agentd.conf
        dest: C:\Zabbix\config\

    - name: Edit zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        regex: '^Server=Server'
        line: Server={{serverzabbix}},{{ serverproxy }}
    - name: Edit zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        regex: '^ServerActive=ServerActive'
        line: ServerActive={{ serverproxyactive }}

    - name: Install Zabbix Agent
      win_command: C:\Zabbix\application\zabbix_agentd.exe -i -c C:\Zabbix\config\zabbix_agentd.conf
      register: installzabbix_out
    
    - name: Start Zabbix Agent
      win_command: sc start "Zabbix Agent"
      register: startzabbix_out