- name: Update Zabbix Agent 5.0.2 - Windows Server
  hosts: all

  tasks:
    - name: Stop Zabbix Agent
      win_command: sc stop "Zabbix Agent"
      register: startzabbix_out

    - name: Delete Zabbix Agent
      win_command: sc delete "Zabbix Agent"
      register: startzabbix_out

    - name: Delete Folder Zabbix Agent
      win_file:
        path: C:\Zabbix\
        state: absent
         
    - name: Create Folder
      win_file:
        path: C:\Zabbix
        state: directory
    - name: Create Folder
      win_file:
        path: C:\Zabbix\application
        state: directory
    - name: Create Folder
      win_file:
        path: C:\Zabbix\config
        state: directory
    - name: Create Folder
      win_file:
        path: C:\Zabbix\log
        state: directory
    - name: Create Folder
      win_file:
        path: C:\Zabbix\scripts
        state: directory

    - win_copy:
        src: /var/lib/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_agentd.conf
        dest: C:\Zabbix\config\

    - name: Edit zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        regex: '^Server=Server'
        line: Server={{serverzabbix}},{{ serverproxy }}
    - name: Edit zabbix_agentd.conf
      win_lineinfile:
        path: C:\Zabbix\config\zabbix_agentd.conf
        regex: '^ServerActive=ServerActive'
        line: ServerActive={{ serverproxyactive }}
     
    - win_copy:
        src: /var/lib/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_agentd.exe
        dest: C:\Zabbix\application\
    
    - win_copy:
        src: /var/lib/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_get.exe
        dest: C:\Zabbix\application\
    
    - win_copy:
        src: /var/lib/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/zabbix_sender.exe
        dest: C:\Zabbix\application\
    - win_copy:
        src: /var/lib/awx/projects/_8__awx_ansible/Zabbix/Agent/Windows/Limpeza_Maquina.bat
        dest: C:\Zabbix\scripts\

    - name: Install Zabbix Agent
      win_command: C:\Zabbix\application\zabbix_agentd.exe -i -c C:\Zabbix\config\zabbix_agentd.conf
      register: installzabbix_out
    
    - name: Start Zabbix Agent
      win_command: sc start "Zabbix Agent"
      register: startzabbix_out