- name: Version Zabbix Agent - Windows Server
  hosts: all

  tasks:
    - name: Check Version Zabbix Agent
      win_command: C:\Zabbix\application\zabbix_agentd.exe -v
      register: installzabbix_out