- name: Create File Zabbix Agent
  hosts: all

  tasks:
  - name: Edit zabbix_agentd.conf
    lineinfile:
      path: /tmp/zabbix_agentd.conf
      regexp: '^Server=Zabbix server'
      line: Server=zbxprd02.qualicorp.com.br


#  - debug:
#        msg: "{{ansible_all_ipv4_addresses}}"

#  - shell: "echo Hostname=$HOSTNAME >> /tmp/zabbix_agentd.conf"