- name: Create File Zabbix Agent
  hosts: all

  tasks:
  - name: create /tmp/zabbix_agentd.conf
    copy:
      dest: /tmp/zabbix_agentd.conf
      owner: root
      group: root
      mode: 0644
      content: |
        Server={{serverzabbix}},stfzbxp01.stefanini.com.br,{{server}}
        ServerActive=stfzbxp01.stefanini.com.br
        StartAgents=5
        DebugLevel=3
        PidFile=/var/run/zabbix/zabbix_agentd.pid
        LogFile=/var/log/zabbix/zabbix_agentd.log
        EnableRemoteCommands=1
        AllowRoot=1
        MaxLinesPerSecond=2
        HostMetadataItem=system.uname
        Hostname={{ansible_hostname}}
  - debug:
        msg: "{{ansible_all_ipv4_addresses}}"

#  - shell: "echo Hostname=$HOSTNAME >> /tmp/zabbix_agentd.conf"