- name: Create User Morphus
  hosts: all

  tasks:
    - user: name=morphus password={{ password }} state=present

    - name: sudo without password for wheel group
      copy:
        content: 'morphus  ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/morphus
        mode: 0440