---
- name: Install Zabbix Agent
  hosts: all
  
  tasks:
  - name: Enable Zabbix Repos
    yum:
      name: https://repo.zabbix.com/zabbix/4.2/rhel/8/x86_64/zabbix-agent-4.2.5-1.el8.x86_64.rpm
      state: present
  
  - name: Install Zabbix Agent
    yum:
      name: zabbix-agent
      state: present
  
  - name: delete /etc/zabbix/zabbix_agentd.conf
    file:
      path: /etc/zabbix/zabbix_agentd.conf
      state: absent
  
 - copy:
        src: /var/lib/awx/projects/_8__awx_ansible/Zabbix/Agent/Linux/zabbix_agentd.conf
        dest: /etc/zabbix/
  
  - name: Edit zabbix_agentd.conf
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server=127.0.0.1'
      line: Server={{serverzabbix}},{{ serverproxy }}
  - name: Edit zabbix_agentd.conf
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^ServerActive=127.0.0.1'
      line:  ServerActive={{ serverproxyactive }}

  - name: Start Zabbix Agent
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes
