---
- name: Install Zabbix Agent
  hosts: all
  #gather_facts: no
  #remote_user: ec2_user
  #become: yes
  #become_user: root
 # vars_files:
 #   - ./zabbix_vars.yml
  tasks:
  - name: Enable Zabbix Repos
    yum:
      name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-agent-4.2.4-1.el7.x86_64.rpm
      state: present
  - name: Install Zabbix Agent
    yum:
      name: zabbix-agent
      state: present
  - name: Start Zabbix Agent
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes
